<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="GetSystemTimeAsTime" Id="{7bc5a8b7-19f7-4eca-ae2b-bdf4cbf64266}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION GetSystemTimeAsTime : TIME
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[GetSystemTimeAsTime := TO_TIME(F_GetSystemTime() / 10000);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>