<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="MAIN_TEST" Id="{c5a022a8-f196-47f6-9c7f-1db1bc1f3d17}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN_TEST
VAR
  FileMemoryTest: FileMemory_Test;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>